#ifndef	STATE_DEF		
#define	STATE_DEF	1
// #define	STATE_LOCAL					5
// Thing states.						
#define	STATE_INIT						0
#define	STATE_NORMAL					1
#define	STATE_COLLISION					2
#define	STATE_ABOUT_TO_REMOVE			3
#define	STATE_REMOVE_ME					4
						
				
#define	STATE_MOVEING					5 //walking ,running, siddling // MA And a moving bit of furniture!
#define	STATE_FDRIVING					6 // furniture drives!!!!!
#define	STATE_IDLE						6 //standing,waiting,
#define	STATE_LANDING					7
#define STATE_FDOOR						7 // Furniture that is a door...
#define	STATE_JUMPING					8
#define	STATE_FIGHTING					9
#define	STATE_FALLING					10
#define	STATE_USE_SCENERY				11
#define	STATE_DOWN						12
#define	STATE_HIT						13
#define	STATE_CHANGE_LOCATION			14 //entering/leaving  buildings/vehicles
#define	STATE_DYING						16
#define	STATE_DEAD						17
#define	STATE_DANGLING					18
#define	STATE_CLIMB_LADDER				19
#define	STATE_HIT_RECOIL				20
#define	STATE_CLIMBING					21
#define	STATE_GUN						22
#define	STATE_SHOOT						23
#define	STATE_DRIVING					24
#define	STATE_NAVIGATING				25
#define	STATE_WAIT						26
#define STATE_FIGHT						27
#define STATE_STAND_UP					28
#define STATE_MAVIGATING				29
#define STATE_GRAPPLING					30	// Using the grappling hook.
#define STATE_GOTOING					31	// Going to a point with no navigation.
#define STATE_CANNING					32	// Coke-can stuff.
#define STATE_CIRCLING					33	// Circling around someone you're going to attack.
#define STATE_HUG_WALL					34	// Circling around someone you're going to attack.
#define STATE_SEARCH					35	// Circling around someone you're going to attack.
#define STATE_CARRY						36
#define STATE_FLOAT						37	// A person floating in the air!
//#define STATE_HOLDING_HUMAN_SHIELD		38	// A person is holding a human shield.

typedef enum
{
	SUB_STATE_FALLING_NORMAL = 0,
	SUB_STATE_WALKING = 1,
	SUB_STATE_RUNNING = 2,
	SUB_STATE_SIDELING = 3,
	SUB_STATE_STOPPING = 4,
	SUB_STATE_HOP_BACK = 5,
	SUB_STATE_STEP_LEFT = 6,
	SUB_STATE_STEP_RIGHT = 7,
	SUB_STATE_FLIPING = 8,
	SUB_STATE_RUNNING_THEN_JUMP = 9,
	SUB_STATE_STOPPING_OT = 10,
	SUB_STATE_WAITING = 11,
	SUB_STATE_WATCHING = 12,
	SUB_STATE_SCRATCHING = 13,
	SUB_STATE_DROP_LAND = 14,
	SUB_STATE_RUNNING_LAND = 15,
	SUB_STATE_WALKING_BACKWARDS = 16,
	SUB_STATE_RUNNING_SKID_STOP = 17,
	SUB_STATE_STOPPING_DEAD = 18,
	SUB_STATE_CRAWLING = 19,
	SUB_STATE_SNEAKING = 20,
	SUB_STATE_STOP_CRAWL = 21,
	SUB_STATE_SLIPPING = 22,
	SUB_STATE_SLIPPING_END = 23,
	SUB_STATE_SIMPLE_ANIM = 24,
	SUB_STATE_RUNNING_VAULT = 25,
	SUB_STATE_SIMPLE_ANIM_OVER = 26,
	SUB_STATE_RUNNING_HIT_WALL = 27,
	SUB_STATE_RUNNING_HALF_BLOCK = 28,
	SUB_STATE_RUN_STOP = 29,
	SUB_STATE_STANDING_JUMP = 30,
	SUB_STATE_STANDING_GRAB_JUMP = 31,
	SUB_STATE_RUNNING_JUMP = 32,
	SUB_STATE_RUNNING_JUMP_FLY = 33,
	SUB_STATE_RUNNING_GRAB_JUMP = 34,
	SUB_STATE_RUNNING_JUMP_LAND = 35,
	SUB_STATE_RUNNING_JUMP_LAND_FAST = 36,
	SUB_STATE_RUNNING_JUMP_FLY_STOP = 37,
	SUB_STATE_STANDING_JUMP_FORWARDS = 38,
	SUB_STATE_STANDING_JUMP_BACKWARDS = 39,
	SUB_STATE_FLYING_KICK = 40,
	SUB_STATE_FLYING_KICK_FALL = 41,
	SUB_STATE_DEATH_LAND = 42,
	SUB_STATE_FLOAT_UP = 43,
	SUB_STATE_FLOAT_BOB = 44,
	SUB_STATE_FLOAT_DOWN = 45,
	SUB_STATE_LATCHING_ON = 50,
	SUB_STATE_LATCHING_OFF = 51,
	SUB_STATE_VAULTING = 52,
	SUB_STATE_CLIMBING = 53,
	SUB_STATE_SIDLE = 60,
	SUB_STATE_IDLE_CROUTCH = 61,
	SUB_STATE_IDLE_CROUTCHING = 62,
	SUB_STATE_IDLE_CROUTCH_ARREST = 63,
	SUB_STATE_IDLE_UNCROUCH = 64,
	SUB_STATE_PUNCH = 90,
	SUB_STATE_KICK = 91,
	SUB_STATE_BLOCK = 92,
	SUB_STATE_GRAPPLE = 93,
	SUB_STATE_GRAPPLEE = 94,
	SUB_STATE_WALL_KICK = 95,
	SUB_STATE_STEP = 96,
	SUB_STATE_STEP_FORWARD = 97,
	SUB_STATE_GRAPPLE_HOLD = 98,
	SUB_STATE_GRAPPLE_HELD = 99,
	SUB_STATE_ESCAPE = 100,
	SUB_STATE_GRAPPLE_ATTACK = 101,
	SUB_STATE_HEADBUTT = 102,
	SUB_STATE_STRANGLE = 103,
	SUB_STATE_HEADBUTTV = 104,
	SUB_STATE_STRANGLEV = 105,
	SUB_STATE_PICKUP_CARRY = 110,
	SUB_STATE_DROP_CARRY = 111,
	SUB_STATE_STAND_CARRY = 112,
	SUB_STATE_PICKUP_CARRY_V = 113,
	SUB_STATE_DROP_CARRY_V = 114,
	SUB_STATE_STAND_CARRY_V = 115,
	SUB_STATE_CARRY_MOVE_V = 116,
	SUB_STATE_ENTERING_VEHICLE = 140,
	SUB_STATE_INSIDE_VEHICLE = 141,
	SUB_STATE_EXITING_VEHICLE = 142,
	SUB_STATE_CIRCLING_CHANGE_POS = 150,
	SUB_STATE_CIRCLING_ATTACK = 151,
	SUB_STATE_CIRCLING_CIRCLE = 152,
	SUB_STATE_CIRCLING_HORROR = 153,
	SUB_STATE_CIRCLING_BACK_OFF = 154,
	SUB_STATE_HUG_WALL_TURN = 156,
	SUB_STATE_HUG_WALL_STAND = 157,
	SUB_STATE_HUG_WALL_STEP_LEFT = 158,
	SUB_STATE_HUG_WALL_STEP_RIGHT = 159,
	SUB_STATE_SEARCH_PRIM = 160,
	SUB_STATE_SEARCH_CORPSE = 161,
	SUB_STATE_HUG_WALL_LOOK_L = 162,
	SUB_STATE_HUG_WALL_LOOK_R = 163,
	SUB_STATE_HUG_WALL_LEAP_OUT = 164,
	SUB_STATE_SEARCH_GETUP = 165,
	SUB_STATE_MOUNTING_BIKE = 145,
	SUB_STATE_RIDING_BIKE = 146,
	SUB_STATE_DISMOUNTING_BIKE = 147,
	SUB_STATE_DEAD_ARREST_TURN_OVER = 170,
	SUB_STATE_DEAD_CUFFED = 171,
	SUB_STATE_DEAD_ARRESTED = 172,
	SUB_STATE_DEAD_INJURED = 173,
	SUB_STATE_DEAD_RESPAWN = 174,
	SUB_STATE_GRAB_TO_DANGLE = 180,
	SUB_STATE_DANGLING = 181,
	SUB_STATE_PULL_UP = 182,
	SUB_STATE_DROP_DOWN = 183,
	SUB_STATE_DROP_DOWN_LAND = 184,
	SUB_STATE_DANGLING_CABLE = 185,
	SUB_STATE_DANGLING_CABLE_FORWARD = 186,
	SUB_STATE_DANGLING_CABLE_BACKWARD = 187,
	SUB_STATE_DROP_DOWN_OFF_FACE = 188,
	SUB_STATE_DEATH_SLIDE = 189,
	SUB_STATE_TRAVERSE_LEFT = 190,
	SUB_STATE_TRAVERSE_RIGHT = 191,
	SUB_STATE_MOUNT_LADDER = 192,
	SUB_STATE_ON_LADDER = 193,
	SUB_STATE_CLIMB_UP_LADDER = 194,
	SUB_STATE_CLIMB_DOWN_LADDER = 195,
	SUB_STATE_CLIMB_OFF_LADDER_BOT = 196,
	SUB_STATE_CLIMB_OFF_LADDER_TOP = 197,
	SUB_STATE_CLIMB_DOWN_ONTO_LADDER = 198,
	SUB_STATE_FLOAT_UP_QUICKLY = 201,
	SUB_STATE_CLIMB_LANDING = 210,
	SUB_STATE_CLIMB_AROUND_WALL = 211,
	SUB_STATE_CLIMB_UP_WALL = 212,
	SUB_STATE_CLIMB_DOWN_WALL = 213,
	SUB_STATE_CLIMB_OVER_WALL = 214,
	SUB_STATE_CLIMB_OFF_BOT_WALL = 215,
	SUB_STATE_CLIMB_LANDING2 = 216,
	SUB_STATE_CLIMB_LEFT_WALL = 217,
	SUB_STATE_CLIMB_RIGHT_WALL = 218,
	SUB_STATE_DRAW_GUN = 220,
	SUB_STATE_AIM_GUN = 221,
	SUB_STATE_SHOOT_GUN = 222,
	SUB_STATE_GUN_AWAY = 223,
	SUB_STATE_DRAW_ITEM = 224,
	SUB_STATE_ITEM_AWAY = 225,
	SUB_STATE_DYING_INITIAL_ANI = 230,
	SUB_STATE_DYING_FINAL_ANI = 231,
	SUB_STATE_DYING_ACTUALLY_DIE = 232,
	SUB_STATE_DYING_KNOCK_DOWN = 233,
	SUB_STATE_DYING_GET_UP_AGAIN = 234,
	SUB_STATE_DYING_PRONE = 235,
	SUB_STATE_DYING_KNOCK_DOWN_WAIT = 236,
	SUB_STATE_TAKE_HIT = 240,
	SUB_STATE_ATTACKING = 241,
	SUB_STATE_ACROBATIC = 242,
	SUB_STATE_DRIVING_ENTER_CAR = 243,
	SUB_STATE_GRAPPLING_PICKUP = 244,
	SUB_STATE_GRAPPLING_WINDUP = 245,
	SUB_STATE_GRAPPLING_RELEASE = 246,
	SUB_STATE_CANNING_PICKUP = 247,
	SUB_STATE_CANNING_RELEASE = 248,
	SUB_STATE_CANNING_GET_SPECIAL = 249,
	SUB_STATE_CANNING_GET_BARREL = 250,
	SUB_STATE_CANNING_GOT_SPECIAL = 251,
	SUB_STATE_HUMAN_SHIELD_HOLD = 252,
	SUB_STATE_CLIMBING_ROPE = 253, /* duplicate value */
} SubState;

#endif
